const STREAM_STATES = Object.freeze({
  IDLE: 'idle',
  CONNECTING: 'connecting',
  STREAMING: 'streaming',
  DISCONNECTED: 'disconnected',
  BACKOFF: 'backoff',
  ENDED: 'ended',
  ERROR_FATAL: 'error-fatal',
});

const BACKPRESSURE_MODES = Object.freeze({
  DROP: 'drop',
  PAUSE: 'pause',
});

const DEFAULT_FLUSH_INTERVAL_MS = 80;
const DEFAULT_FLUSH_BATCH_SIZE = 200;
const DEFAULT_REORDER_WINDOW_MS = 0;
const DEFAULT_RING_BUFFER_CAPACITY = 50000;
const INITIAL_BACKOFF_MS = 500;
const MAX_BACKOFF_MS = 30000;
const DEDUP_FINGERPRINT_CACHE_SIZE = 300;

module.exports = {
  STREAM_STATES,
  BACKPRESSURE_MODES,
  DEFAULT_FLUSH_INTERVAL_MS,
  DEFAULT_FLUSH_BATCH_SIZE,
  DEFAULT_REORDER_WINDOW_MS,
  DEFAULT_RING_BUFFER_CAPACITY,
  INITIAL_BACKOFF_MS,
  MAX_BACKOFF_MS,
  DEDUP_FINGERPRINT_CACHE_SIZE,
};
